# Generated by Django 4.2.14 on 2024-08-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_kullanici_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='kullaniciAdi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
